// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.3
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:149

#ifndef _TAO_IDL__TMP__TELEGRAMALARMC_H_
#define _TAO_IDL__TMP__TELEGRAMALARMC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/AnyTypeCode/TypeCode.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "baciC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 4 || TAO_MICRO_VERSION != 3
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_root/root_ch.cpp:157
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:35

namespace Telegram
{

  // TAO_IDL - Generated from
  // be/be_interface.cpp:748

#if !defined (_TELEGRAM_TELEGRAMALARM__VAR_OUT_CH_)
#define _TELEGRAM_TELEGRAMALARM__VAR_OUT_CH_

  class telegramalarm;
  typedef telegramalarm *telegramalarm_ptr;
  typedef TAO_Objref_Var_T<telegramalarm> telegramalarm_var;
  typedef TAO_Objref_Out_T<telegramalarm> telegramalarm_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:40

  class  telegramalarm
    : public virtual ::ACS::ACSComponent
  
  {
  public:
    friend class TAO::Narrow_Utils<telegramalarm>;

    // TAO_IDL - Generated from
    // be/be_type.cpp:304

    typedef telegramalarm_ptr _ptr_type;
    typedef telegramalarm_var _var_type;
    typedef telegramalarm_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static telegramalarm_ptr _duplicate (telegramalarm_ptr obj);

    static void _tao_release (telegramalarm_ptr obj);

    static telegramalarm_ptr _narrow (::CORBA::Object_ptr obj);
    static telegramalarm_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static telegramalarm_ptr _nil (void);

    virtual void addValue (
      const char * node,
      const char * baciName,
      const char * timeBaci,
      ::CORBA::Double value);

    virtual void send_status (
      const char * chatid);

    virtual void send_values (
      const char * chatid,
      const char * data,
      const char * baci);

    virtual void send_subscribe (
      const char * chatid,
      const char * data);

    virtual void send_unsubscribe (
      const char * chatid,
      const char * data);

    virtual void send_unsubscribeall (
      const char * chatid);

    virtual void send_subscribeall (
      const char * chatid);

    virtual void send_echo_all (
      const char * message);

    virtual void clearAll (
      void);

    virtual char * getOptions (
      void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    telegramalarm (void);

    // Concrete non-local interface only.
    telegramalarm (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    telegramalarm (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);

    virtual ~telegramalarm (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    telegramalarm (const telegramalarm &);

    void operator= (const telegramalarm &);
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:34

  extern  ::CORBA::TypeCode_ptr const _tc_telegramalarm;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:64

} // module Telegram

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:145

#if !defined (_TELEGRAM_TELEGRAMALARM__ARG_TRAITS_)
#define _TELEGRAM_TELEGRAMALARM__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::Telegram::telegramalarm>
    : public
        Object_Arg_Traits_T<
            ::Telegram::telegramalarm_ptr,
            ::Telegram::telegramalarm_var,
            ::Telegram::telegramalarm_out,
            TAO::Objref_Traits<Telegram::telegramalarm>,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_TELEGRAM_TELEGRAMALARM__TRAITS_)
#define _TELEGRAM_TELEGRAMALARM__TRAITS_

  template<>
  struct  Objref_Traits< ::Telegram::telegramalarm>
  {
    static ::Telegram::telegramalarm_ptr duplicate (
        ::Telegram::telegramalarm_ptr p);
    static void release (
        ::Telegram::telegramalarm_ptr p);
    static ::Telegram::telegramalarm_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Telegram::telegramalarm_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:41



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Telegram
{
   void operator<<= ( ::CORBA::Any &, telegramalarm_ptr); // copying
   void operator<<= ( ::CORBA::Any &, telegramalarm_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, telegramalarm_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, Telegram::telegramalarm_ptr); // copying
 void operator<<= (::CORBA::Any &, Telegram::telegramalarm_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Telegram::telegramalarm_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:41

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Telegram::telegramalarm_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, Telegram::telegramalarm_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1700
#if defined (__ACE_INLINE__)
#include "telegramalarmC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

