-- TMCDB SQL TABLE DEFINITIONS Version 2.2.1 2010-08-22T0000:00:00.0
--
-- /////////////////////////////////////////////////////////////////
-- // WARNING!  DO NOT MODIFY THIS FILE!                          //
-- //  ---------------------------------------------------------  //
-- // | This is generated code!  Do not modify this file.       | //
-- // | Any changes will be lost when the file is re-generated. | //
-- //  ---------------------------------------------------------  //
-- /////////////////////////////////////////////////////////////////

DROP TABLE Holography CASCADE CONSTRAINTS PURGE;
DROP TABLE ReceiverQualityParameters CASCADE CONSTRAINTS PURGE;
DROP TABLE ReceiverQuality CASCADE CONSTRAINTS PURGE;
DROP TABLE AntennaEfficiency CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_AcaCorrDelays CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_AntennaToPad CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_Pad CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_Antenna CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_AntennaDelay CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_XPDelay CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_LODelay CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_IFDelay CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_FEDelay CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_FocusModelCoeffOffset CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_FocusModelCoeff CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_PointingModelCoeffOffset CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_PointingModelCoeff CASCADE CONSTRAINTS PURGE;
DROP TABLE BL_VersionInfo CASCADE CONSTRAINTS PURGE;
DROP TABLE AntennaToFrontEnd CASCADE CONSTRAINTS PURGE;
DROP TABLE SBExecution CASCADE CONSTRAINTS PURGE;
DROP TABLE AntennaToArray CASCADE CONSTRAINTS PURGE;
DROP TABLE Array CASCADE CONSTRAINTS PURGE;
DROP TABLE AssemblyOnline CASCADE CONSTRAINTS PURGE;
DROP TABLE BaseElementOnline CASCADE CONSTRAINTS PURGE;
DROP TABLE MonitorData CASCADE CONSTRAINTS PURGE;
DROP TABLE MonitorPoint CASCADE CONSTRAINTS PURGE;
DROP TABLE DefaultMonitorPoint CASCADE CONSTRAINTS PURGE;
DROP TABLE DefaultBaciProperty CASCADE CONSTRAINTS PURGE;
DROP TABLE DefaultComponent CASCADE CONSTRAINTS PURGE;
DROP TABLE FocusModelCoeffOffset CASCADE CONSTRAINTS PURGE;
DROP TABLE FocusModelCoeff CASCADE CONSTRAINTS PURGE;
DROP TABLE FocusModel CASCADE CONSTRAINTS PURGE;
DROP TABLE PointingModelCoeffOffset CASCADE CONSTRAINTS PURGE;
DROP TABLE PointingModelCoeff CASCADE CONSTRAINTS PURGE;
DROP TABLE PointingModel CASCADE CONSTRAINTS PURGE;
DROP TABLE DefaultCanAddress CASCADE CONSTRAINTS PURGE;
DROP TABLE AssemblyStartup CASCADE CONSTRAINTS PURGE;
DROP TABLE BaseElementStartup CASCADE CONSTRAINTS PURGE;
DROP TABLE Startup CASCADE CONSTRAINTS PURGE;
DROP TABLE CorrelatorBin CASCADE CONSTRAINTS PURGE;
DROP TABLE CorrStationBin CASCADE CONSTRAINTS PURGE;
DROP TABLE CorrQuadrantRack CASCADE CONSTRAINTS PURGE;
DROP TABLE CorrQuadrant CASCADE CONSTRAINTS PURGE;
DROP TABLE XPDelay CASCADE CONSTRAINTS PURGE;
DROP TABLE LODelay CASCADE CONSTRAINTS PURGE;
DROP TABLE IFDelay CASCADE CONSTRAINTS PURGE;
DROP TABLE FEDelay CASCADE CONSTRAINTS PURGE;
DROP TABLE HolographyTowerToPad CASCADE CONSTRAINTS PURGE;
DROP TABLE WeatherStationToPad CASCADE CONSTRAINTS PURGE;
DROP TABLE AntennaToPad CASCADE CONSTRAINTS PURGE;
DROP TABLE HolographyTower CASCADE CONSTRAINTS PURGE;
DROP TABLE AOSTiming CASCADE CONSTRAINTS PURGE;
DROP TABLE CentralLO CASCADE CONSTRAINTS PURGE;
DROP TABLE WeatherStationController CASCADE CONSTRAINTS PURGE;
DROP TABLE PhotonicReference CASCADE CONSTRAINTS PURGE;
DROP TABLE FrontEnd CASCADE CONSTRAINTS PURGE;
DROP TABLE Pad CASCADE CONSTRAINTS PURGE;
DROP TABLE AcaCorrDelays CASCADE CONSTRAINTS PURGE;
DROP TABLE Antenna CASCADE CONSTRAINTS PURGE;
DROP TABLE AcaCorrSet CASCADE CONSTRAINTS PURGE;
DROP TABLE BaseElement CASCADE CONSTRAINTS PURGE;
DROP TABLE AssemblyRole CASCADE CONSTRAINTS PURGE;
DROP TABLE Assembly CASCADE CONSTRAINTS PURGE;
DROP TABLE HwSchemas CASCADE CONSTRAINTS PURGE;
DROP TABLE AssemblyType CASCADE CONSTRAINTS PURGE;
DROP TABLE LRUType CASCADE CONSTRAINTS PURGE;
DROP TABLE SystemCounters CASCADE CONSTRAINTS PURGE;
DROP TABLE HWConfiguration CASCADE CONSTRAINTS PURGE;
